services:
  ollama:
    image: docker.io/mazurkatarzyna/cve-2024-7764-ollama-mistral:latest
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ollama list || exit 1
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
    network_mode: host
  db:
    image: docker.io/mazurkatarzyna/cve-2024-7764-postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    network_mode: host
  chroma:  
    image: docker.io/mazurkatarzyna/cve-2024-7764-chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    network_mode: host
  app:
    image: mazurkatarzyna/cve-2024-7764-app:latest   
    network_mode: host
    depends_on:
     - db

volumes:
  ollama_data:
  index_data:
    driver: local
