version: '3.1'

services:

  wordpress:
    image: ghcr.io/mazurkatarzynaumcs/cve-2025-34077-wordpress:latest
    restart: always     
    ports:
      - 3003:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      MARIADB_HOST: 127.0.0.1
    volumes:
      - wordpress:/var/www/html
      - wordpress-wp-content:/var/www/html/wp-content
      - wordpress-plugins:/var/www/html/wp-content/plugins
  db:
    image: ghcr.io/mazurkatarzynaumcs/cve-2025-34077-mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    ports:
      - "127.0.0.1:33060:33060"

volumes:
  wordpress:
  wordpress-wp-content:
  wordpress-plugins:
  db:
