services:
  db:
    image: docker.io/mazurkatarzyna/postgres-cve-2024-5225:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"

  litellm:
    image: docker.io/mazurkatarzyna/cve-2024-5225:latest
    ports:
      - "4000:4000"  
    environment:
        DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"


